"""Add schedule_shifts table and remove shifts JSON from schedules

Revision ID: 18722d8883ca
Revises: 
Create Date: 2025-12-11 13:18:57.373538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18722d8883ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- SAFE MIGRATION ---
    # 1. ลบ column shifts ออกจาก schedules (ถ้ามี)
    with op.batch_alter_table('schedules') as batch_op:
        batch_op.drop_column('shifts')

    # 2. ข้ามการสร้างตาราง schedule_shifts เพราะมีอยู่แล้ว
    # op.create_table('schedule_shifts', ...)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('guards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guardId', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('bankAccountNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bankCode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('firstName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='คำนำหน้า'),
    sa.Column('birthDate', sa.DATE(), autoincrement=False, nullable=True, comment='วันเดือนปีเกิด'),
    sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='สัญชาติ'),
    sa.Column('religion', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='ศาสนา'),
    sa.Column('addressIdCard', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='ที่อยู่ตามบัตรประชาชน'),
    sa.Column('addressCurrent', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='ที่อยู่ปัจจุบัน'),
    sa.Column('education', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='วุฒิการศึกษา'),
    sa.Column('licenseNumber', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='เลขที่บัตร/ใบอนุญาต'),
    sa.Column('licenseExpiry', sa.DATE(), autoincrement=False, nullable=True, comment='วันหมดอายุใบอนุญาต'),
    sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=True, comment='วันเริ่มปฏิบัติงาน'),
    sa.Column('bankAccountName', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='ชื่อบัญชี'),
    sa.Column('idCardNumber', sa.VARCHAR(length=13), autoincrement=False, nullable=True, comment='เลขบัตรประชาชน 13 หลัก'),
    sa.Column('maritalStatus', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='สถานภาพสมรส'),
    sa.Column('spouseName', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='ชื่อคู่สมรส'),
    sa.Column('emergencyContactName', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='ชื่อผู้ติดต่อฉุกเฉิน'),
    sa.Column('emergencyContactPhone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='เบอร์โทรฉุกเฉิน'),
    sa.Column('emergencyContactRelation', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='ความสัมพันธ์'),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('salaryType', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('paymentMethod', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guards_pkey'))
    )
    op.create_index(op.f('ix_guards_id'), 'guards', ['id'], unique=False)
    op.create_index(op.f('ix_guards_guardId'), 'guards', ['guardId'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('serviceCode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('serviceName', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('hiringRate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('diligenceBonus', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('sevenDayBonus', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('pointBonus', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey')),
    sa.UniqueConstraint('serviceCode', name=op.f('services_serviceCode_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('idx_services_code'), 'services', ['serviceCode'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sites_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('siteCode', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('customerId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customerCode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customerName', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('contractStartDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('contractEndDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('subDistrict', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postalCode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('contactPerson', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('employmentDetails', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contractedServices', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sites_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_sites_siteCode'), 'sites', ['siteCode'], unique=True)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('schedule_shifts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('schedule_shifts_schedule_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('schedule_shifts_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('schedule_shifts_pkey'))
    )
    op.create_index(op.f('ix_schedule_shifts_staff_id'), 'schedule_shifts', ['staff_id'], unique=False)
    op.create_index(op.f('ix_schedule_shifts_schedule_id'), 'schedule_shifts', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_shifts_id'), 'schedule_shifts', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('staffId', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('bankAccountNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bankCode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('firstName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=True, comment='วันเริ่มงาน'),
    sa.Column('birthDate', sa.DATE(), autoincrement=False, nullable=True, comment='วันเกิด'),
    sa.Column('salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='เงินเดือน'),
    sa.Column('salaryType', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='ประเภทเงินเดือน: รายเดือน, รายวัน, รายชั่วโมง'),
    sa.Column('paymentMethod', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='วิธีรับเงิน: โอนเข้าบัญชี, เงินสด, เช็ค'),
    sa.Column('idCardNumber', sa.VARCHAR(length=13), autoincrement=False, nullable=True, comment='เลขบัตรประชาชน'),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='ตำแหน่งงาน'),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='แผนก'),
    sa.Column('title', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_pkey'))
    )
    op.create_index(op.f('ix_staff_staffId'), 'staff', ['staffId'], unique=True)
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('roleId', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('daily_advances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('docNumber', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('items', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdBy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('approvedBy', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_advances_pkey'))
    )
    op.create_index(op.f('ix_daily_advances_id'), 'daily_advances', ['id'], unique=False)
    op.create_index(op.f('ix_daily_advances_docNumber'), 'daily_advances', ['docNumber'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entityType', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entityId', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entityName', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oldData', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('newData', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ipAddress', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_userId'), 'audit_logs', ['userId'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entityType'), 'audit_logs', ['entityType'], unique=False)
    op.create_index(op.f('ix_audit_logs_entityId'), 'audit_logs', ['entityId'], unique=False)
    op.create_index(op.f('ix_audit_logs_createdAt'), 'audit_logs', ['createdAt'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('businessType', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('taxId', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('subDistrict', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postalCode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('contactPerson', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('secondaryContact', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('paymentTerms', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('mapLink', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('billing', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_table('banks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('shortNameEN', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('banks_pkey'))
    )
    op.create_index(op.f('ix_banks_id'), 'banks', ['id'], unique=False)
    op.create_index(op.f('ix_banks_code'), 'banks', ['code'], unique=True)
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scheduleDate', sa.DATE(), autoincrement=False, nullable=False, comment='วันที่จัดตารางงาน'),
    sa.Column('siteId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('siteName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('shifts', sa.TEXT(), autoincrement=False, nullable=False, comment='ข้อมูลกะงาน (JSON) - เก็บ day shift และ night shift'),
    sa.Column('totalGuardsDay', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('totalGuardsNight', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('totalGuards', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('createdBy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], name=op.f('fk_schedule_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['siteId'], ['sites.id'], name=op.f('fk_schedule_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey')),
    sa.UniqueConstraint('scheduleDate', 'siteId', name=op.f('uk_schedule_date_site'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='ตารางงาน - จัดพนักงานตามหน่วยงานและวันที่'
    )
    op.create_index(op.f('idx_schedules_site_id'), 'schedules', ['siteId'], unique=False)
    op.create_index(op.f('idx_schedules_date_site'), 'schedules', ['scheduleDate', 'siteId'], unique=False)
    op.create_index(op.f('idx_schedules_date'), 'schedules', ['scheduleDate'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('roleId', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
    sa.UniqueConstraint('name', name=op.f('roles_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('roleId', name=op.f('roles_roleId_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    # ### end Alembic commands ###
